brand_dict = {"1792 Full Proof":"1792",
"1792 Port Finish":"1792",
"1792 Ridgemont Reserve":"1792",
"1792 Small Batch":"1792",
"1792 Sweet Wheat":"1792",
"Aberfeldy 12":"Aberfeldy",
"Aberfeldy 21":"Aberfeldy",
"Aberlour 10":"Aberlour",
"Aberlour 12 Double Cask Matured":"Aberlour",
"Aberlour 12 Non Chill Filtered":"Aberlour",
"Aberlour 16":"Aberlour",
"Aberlour 18":"Aberlour",
"Aberlour A'bunadh batch #39":"Aberlour",
"Aberlour A'bunadh batch #42":"Aberlour",
"Aberlour A'bunadh batch #45":"Aberlour",
"Aberlour A'bunadh batch #46":"Aberlour",
"Aberlour A'bunadh batch #47":"Aberlour",
"Alberta Premium Dark Horse":"Alberta Premium",
"Amrut Cask Strength":"Amrut",
"Amrut Fusion":"Amrut",
"Amrut Intermediate Sherry":"Amrut",
"Amrut Kadhambam":"Amrut",
"Amrut Peated Cask Strength":"Amrut",
"Amrut Portonova":"Amrut",
"Amrut Spectrum 004":"Amrut",
"AnCnoc 12":"AnCnoc",
"AnCnoc 16":"AnCnoc",
"AnCnoc Flaughter":"AnCnoc",
"Angel's Envy Bourbon":"Angel's Envy",
"Angel's Envy Cask Strength":"Angel's Envy",
"Angel's Envy Rye":"Angel's Envy",
"Ardbeg 10":"Ardbeg",
"Ardbeg Airigh Nam Beist 1990":"Ardbeg",
"Ardbeg Alligator":"Ardbeg",
"Ardbeg An Oa":"Ardbeg",
"Ardbeg Ardbog":"Ardbeg",
"Ardbeg Auriverdes":"Ardbeg",
"Ardbeg Corryvreckan":"Ardbeg",
"Ardbeg Dark Cove Committee Release":"Ardbeg",
"Ardbeg Day":"Ardbeg",
"Ardbeg Drum Committee Release":"Ardbeg",
"Ardbeg Galileo":"Ardbeg",
"Ardbeg Grooves Committee Release":"Ardbeg",
"Ardbeg Perpetuum":"Ardbeg",
"Ardbeg Supernova 2014":"Ardbeg",
"Ardbeg Uigeadail":"Ardbeg",
"Ardmore 12 Port Wood Finish":"Ardmore",
"Ardmore Legacy":"Ardmore",
"Ardmore Traditional Cask Peated":"Ardmore",
"Arran 10":"Arran",
"Arran 12 Cask Strength":"Arran",
"Arran 14":"Arran",
"Arran Amarone Cask Finish":"Arran",
"Arran Port Cask Finish":"Arran",
"Arran Sauternes Cask Finish":"Arran",
"Auchentoshan 12":"Auchentoshan",
"Auchentoshan Classic":"Auchentoshan",
"Auchentoshan Three Wood":"Auchentoshan",
"Auchentoshan Valinch":"Auchentoshan",
"Aultmore 12":"Aultmore",
"Baker's 107":"Baker's",
"Balblair 1990 2nd Release":"Balblair",
"Balcones Brimstone":"Balcones",
"Balcones Texas Single Malt":"Balcones",
"Balvenie 12 Doublewood":"Balvenie",
"Balvenie 12 Single Barrel First Fill":"Balvenie",
"Balvenie 14 Caribbean Cask":"Balvenie",
"Balvenie 15 Single Barrel":"Balvenie",
"Balvenie 15 Single Barrel Sherry Cask":"Balvenie",
"Balvenie 17 Doublewood":"Balvenie",
"Balvenie 17 Madeira Cask":"Balvenie",
"Balvenie 17 Peated Cask":"Balvenie",
"Balvenie 21 Portwood":"Balvenie",
"Balvenie Tun 1401 Batch #3":"Balvenie",
"Basil Hayden's":"Basil Hayden's",
"BenRiach 10 Curiositas":"BenRiach",
"BenRiach 12":"BenRiach",
"BenRiach 12 Importanticus Fumosus":"BenRiach",
"BenRiach 12 Sherry Matured":"BenRiach",
"BenRiach 16":"BenRiach",
"BenRiach 17 Solstice":"BenRiach",
"Benrinnes 14 1999 Lady of the Glen":"Benrinnes",
"Benrinnes 23":"Benrinnes",
"Benromach 10":"Benromach",
"Benromach 10 100 Proof":"Benromach",
"Bernheim Original Small Batch Wheat Whiskey":"Bernheim",
"Black Bottle":"Black Bottle",
"Black Grouse":"The Famous Grouse",
"Black Maple Hill":"Black Maple Hill",
"Blanton's Original Single Barrel":"Blanton's",
"Blanton's Straight from the Barrel":"Blanton's",
"Booker's 25th Anniversary":"Booker's",
"Booker's Bourbon":"Booker's",
"Booker's Rye":"Booker's",
"Bowmore 12":"Bowmore",
"Bowmore 15 Darkest":"Bowmore",
"Bowmore 15 Laimrig":"Bowmore",
"Bowmore 18":"Bowmore",
"Bowmore Legend":"Bowmore",
"Bowmore Vault Edition 1st Release":"Bowmore",
"Breckenridge Bourbon":"Breckenridge",
"Bruichladdich 21 Cuvee 407 PX":"Bruichladdich",
"Bruichladdich Black Art 2.2":"Bruichladdich",
"Bruichladdich Black Art 3.1":"Bruichladdich",
"Bruichladdich Black Art 4.1":"Bruichladdich",
"Bruichladdich Octomore 4.2_167 Comus":"Bruichladdich",
"Bruichladdich Octomore 6.1":"Bruichladdich",
"Bruichladdich Octomore 6.2":"Bruichladdich",
"Bruichladdich Octomore 6.3":"Bruichladdich",
"Bruichladdich Octomore 7.2":"Bruichladdich",
"Bruichladdich Octomore 7.3":"Bruichladdich",
"Bruichladdich Octomore 7.4":"Bruichladdich",
"Bruichladdich Port Charlotte 10":"Bruichladdich",
"Bruichladdich Port Charlotte 2007 CC:01":"Bruichladdich",
"Bruichladdich Port Charlotte An Turas Mor":"Bruichladdich",
"Bruichladdich Port Charlotte PC12 Oileanach Furachail":"Bruichladdich",
"Bruichladdich Port Charlotte PC7 Sin an Doigh Ileach":"Bruichladdich",
"Bruichladdich Port Charlotte Scottish Barley":"Bruichladdich",
"Bruichladdich Port Charlotte The Peat Project":"Bruichladdich",
"Bruichladdich Rocks":"Bruichladdich",
"Bruichladdich Scottish Barley The Classic Laddie":"Bruichladdich",
"Bruichladdich The Laddie Sixteen":"Bruichladdich",
"Bruichladdich The Laddie Ten":"Bruichladdich",
"Buchanan's 12 De Luxe":"Buchanan's",
"Buffalo Trace":"Buffalo Trace",
"Buffalo Trace White Dog Mash #1":"Buffalo Trace",
"Bulleit Bourbon":"Bulleit",
"Bulleit Bourbon 10":"Bulleit",
"Bulleit Rye":"Bulleit",
"Bunnahabhain 12":"Bunnahabhain",
"Bunnahabhain 14 Pedro Ximenez Finish":"Bunnahabhain",
"Bunnahabhain 18":"Bunnahabhain",
"Bunnahabhain 25":"Bunnahabhain",
"Bunnahabhain Toiteach":"Bunnahabhain",
"Bushmills 10":"Bushmills",
"Bushmills Black Bush":"Bushmills",
"Caol Ila 12":"Caol Ila",
"Caol Ila 15 Unpeated":"Caol Ila",
"Caol Ila 18":"Caol Ila",
"Caol Ila Distiller's Edition":"Caol Ila",
"Cardhu 12":"Cardhu",
"Chivas Regal 12":"Chivas",
"Clynelish 14":"Clynelish",
"Collingwood 21":"Collingwood",
"Colonel E.H. Taylor Barrel Proof":"Colonel E.H. Taylor",
"Colonel E.H. Taylor Cured Oak":"Colonel E.H. Taylor",
"Colonel E.H. Taylor Single Barrel":"Colonel E.H. Taylor",
"Colonel E.H. Taylor Small Batch":"Colonel E.H. Taylor",
"Colonel E.H. Taylor Straight Rye":"Colonel E.H. Taylor",
"Compass Box 3 Year Old Deluxe":"Compass Box",
"Compass Box Asyla":"Compass Box",
"Compass Box Enlightenment":"Compass Box",
"Compass Box Flaming Heart":"Compass Box",
"Compass Box Flaming Heart 15th Anniversary Edition":"Compass Box",
"Compass Box Great King St. Artist's Blend":"Compass Box",
"Compass Box Great King St. Glasgow Blend":"Compass Box",
"Compass Box Hedonism":"Compass Box",
"Compass Box No Name":"Compass Box",
"Compass Box Oak Cross":"Compass Box",
"Compass Box Peat Monster":"Compass Box",
"Compass Box Spice Tree":"Compass Box",
"Compass Box The Lost Blend":"Compass Box",
"Compass Box This is Not a Luxury Whisky":"Compass Box",
"Connemara Peated":"Connemara",
"Cragganmore 12":"Cragganmore",
"Craigellachie 13":"Craigellachie",
"Crown Royal":"Crown Royal",
"Crown Royal Hand Selected Barrel":"Crown Royal",
"Crown Royal Northern Harvest Rye":"Crown Royal",
"Cutty Sark":"Cutty Sark",
"Dalmore 12":"Dalmore",
"Dalmore 1263 King Alexander III":"Dalmore",
"Dalmore 15":"Dalmore",
"Dalmore Cigar Malt":"Dalmore",
"Dalwhinnie 15":"Dalwhinnie",
"Deanston 12":"Deanston",
"Deanston Virgin Oak":"Deanston",
"Dewar's 12":"Dewar's",
"Dewar's White Label":"Dewar's",
"Dimple Pinch 15":"Dimple Pinch",
"Eagle Rare 10":"Eagle Rare",
"Eagle Rare 17":"Eagle Rare",
"Edradour 10":"Edradour",
"Elijah Craig 12":"Elijah Craig",
"Elijah Craig 18":"Elijah Craig",
"Elijah Craig Barrel Proof":"Elijah Craig",
"Elmer T. Lee":"Elmer T. Lee",
"Evan Williams Black Label":"Evan Williams",
"Evan Williams Single Barrel 2003":"Evan Williams",
"Evan Williams Single Barrel 2004":"Evan Williams",
"Evan Williams White Label Bottled in Bond":"Evan Williams",
"Famous Grouse":"Famous Grouse",
"Finlaggan Old Reserve":"Finlaggan",
"Forty Creek Barrel Select":"Forty Creek",
"Four Roses Single Barrel":"Four Roses",
"Four Roses Single Barrel Limited Edition 2014":"Four Roses",
"Four Roses Single Barrel Private Selection OBSF":"Four Roses",
"Four Roses Single Barrel Private Selection OBSK":"Four Roses",
"Four Roses Single Barrel Private Selection OBSQ":"Four Roses",
"Four Roses Single Barrel Private Selection OBSV":"Four Roses",
"Four Roses Single Barrel Private Selection OESF":"Four Roses",
"Four Roses Single Barrel Private Selection OESK":"Four Roses",
"Four Roses Single Barrel Private Selection OESQ":"Four Roses",
"Four Roses Small Batch":"Four Roses",
"Four Roses Small Batch Limited Edition 2013 125th Anniversary":"Four Roses",
"Four Roses Small Batch Limited Edition 2014":"Four Roses",
"Four Roses Small Batch Limited Edition 2015":"Four Roses",
"Four Roses Small Batch Limited Edition 2016":"Four Roses",
"Four Roses Yellow Label":"Four Roses",
"George Dickel No. 12":"George Dickel",
"George T. Stagg 2012":"George T. Stagg",
"George T. Stagg 2013":"George T. Stagg",
"George T. Stagg 2014":"George T. Stagg",
"George T. Stagg 2017":"George T. Stagg",
"Glen Garioch 12":"Glen Garioch",
"Glen Garioch Founder's Reserve":"Glen Garioch",
"Glen Grant 10":"Glen Grant",
"Glen Moray 12":"Glen Moray",
"GlenDronach 12 Original":"GlenDronach",
"GlenDronach 15 Revival":"GlenDronach",
"GlenDronach 18 Allardice":"GlenDronach",
"GlenDronach 21 Parliament":"GlenDronach",
"GlenDronach Cask Strength":"GlenDronach",
"Glenfarclas 10":"Glenfarclas",
"Glenfarclas 105 Cask Strength":"Glenfarclas",
"Glenfarclas 12":"Glenfarclas",
"Glenfarclas 15":"Glenfarclas",
"Glenfarclas 17":"Glenfarclas",
"Glenfarclas 21":"Glenfarclas",
"Glenfarclas 25":"Glenfarclas",
"Glenfarclas 40":"Glenfarclas",
"Glenfiddich 12":"Glenfiddich",
"Glenfiddich 14 Bourbon Barrel Reserve":"Glenfiddich",
"Glenfiddich 14 Rich Oak":"Glenfiddich",
"Glenfiddich 15":"Glenfiddich",
"Glenfiddich 15 Distillery Edition":"Glenfiddich",
"Glenfiddich 18":"Glenfiddich",
"Glenfiddich 21 Gran Reserva":"Glenfiddich",
"Glenfiddich Experimental Series IPA Cask Finish":"Glenfiddich",
"Glenfiddich Snow Phoenix":"Glenfiddich",
"Glengoyne 10":"Glengoyne",
"Glengoyne 12":"Glengoyne",
"Glengoyne 15":"Glengoyne",
"Glengoyne 17":"Glengoyne",
"Glengoyne 18":"Glengoyne",
"Glengoyne 21":"Glengoyne",
"Glengoyne 25":"Glengoyne",
"Glenkinchie 12":"Glenkinchie",
"Glenlivet 12":"Glenlivet",
"Glenlivet 15 French Oak Reserve":"Glenlivet",
"Glenlivet 16 Nadurra":"Glenlivet",
"Glenlivet 18":"Glenlivet",
"Glenlivet 21 Archive":"Glenlivet",
"Glenlivet 25":"Glenlivet",
"Glenlivet Nadurra Oloroso":"Glenlivet",
"Glenmorangie 10 Original":"Glenmorangie",
"Glenmorangie 12 Quinta Ruban":"Glenmorangie",
"Glenmorangie 18":"Glenmorangie",
"Glenmorangie Artein":"Glenmorangie",
"Glenmorangie Astar":"Glenmorangie",
"Glenmorangie Ealanta":"Glenmorangie",
"Glenmorangie Lasanta":"Glenmorangie",
"Glenmorangie Nectar D'Or 12":"Glenmorangie",
"Glenmorangie Signet":"Glenmorangie",
"Glenrothes 1998":"Glenrothes",
"Glenrothes Select Reserve":"Glenrothes",
"Green Spot":"Green Spot",
"Hakushu 12":"Hakushu",
"Hazelburn 10":"Hazelburn",
"Heaven Hill 6 Bottled in Bond":"Heaven Hill",
"Henry McKenna 10 Single Barrel":"Henry McKenna",
"Hibiki 12":"Hibiki",
"Hibiki 17":"Hibiki",
"Hibiki Japanese Harmony":"Hibiki",
"High West A Midwinter Nights Dram":"High West",
"High West Bourye":"High West",
"High West Campfire":"High West",
"High West Double Rye":"High West",
"High West Rendezvous Rye":"High West",
"High West Son of Bourye":"High West",
"High West Yippee Ki Yay":"High West",
"Highland Park 12":"Highland Park",
"Highland Park 15":"Highland Park",
"Highland Park 15 Freya":"Highland Park",
"Highland Park 15 Loki":"Highland Park",
"Highland Park 18":"Highland Park",
"Highland Park 25":"Highland Park",
"Highland Park Dark Origins":"Highland Park",
"J&B Rare":"J&B Rare",
"J.P. Wiser's 18":"J.P. Wiser's",
"J.P. Wiser's Dissertation":"J.P. Wiser's",
"J.P. Wiser's Last Barrels":"J.P. Wiser's",
"Jack Daniel's Old No. 7":"Jack Daniels",
"Jack Daniel's Single Barrel":"Jack Daniels",
"Jameson":"Jameson",
"Jefferson's 10 Rye Whiskey":"Jefferson's",
"Jim Beam Black 8 Double Aged":"Jim Beam",
"Jim Beam Bonded":"Jim Beam",
"Jim Beam Devil's Cut":"Jim Beam",
"Jim Beam Signature Craft 12":"Jim Beam",
"Jim Beam White Label":"Jim Beam",
"Johnnie Walker Black Label":"Johnnie Walker",
"Johnnie Walker Blue Label":"Johnnie Walker",
"Johnnie Walker Double Black":"Johnnie Walker",
"Johnnie Walker Gold Label":"Johnnie Walker",
"Johnnie Walker Green Label":"Johnnie Walker",
"Johnnie Walker Platinum Label":"Johnnie Walker",
"Johnnie Walker Red Label":"Johnnie Walker",
"Johnny Drum Private Stock":"Johnny Drum",
"Jura 10 Origin":"Jura",
"Jura 16":"Jura",
"Jura Prophecy":"Jura",
"Jura Superstition":"Jura",
"Kavalan Concertmaster":"Kavalan",
"Kavalan Solist Ex-Bourbon":"Kavalan",
"Kavalan Solist Sherry":"Kavalan",
"Kavalan Solist Vinho Barrique":"Kavalan",
"Kilchoman Coull Point":"Kilchoman",
"Kilchoman Loch Gorm":"Kilchoman",
"Kilchoman Machir Bay":"Kilchoman",
"Kilchoman Port Cask Matured":"Kilchoman",
"Kilchoman Sanaig":"Kilchoman",
"Kilchoman Sherry Cask Release":"Kilchoman",
"Kilkerran 12":"Kilkerran",
"Knob Creek 9 Small Batch":"Knob Creek",
"Knob Creek Rye":"Knob Creek",
"Knob Creek Single Barrel Reserve":"Knob Creek",
"Lagavulin 12":"Lagavulin",
"Lagavulin 16":"Lagavulin",
"Lagavulin 1995 Distillers Edition":"Lagavulin",
"Lagavulin 1997 Distillers Edition":"Lagavulin",
"Lagavulin 8":"Lagavulin",
"Laphroaig 10":"Laphroaig",
"Laphroaig 10 Cask Strength":"Laphroaig",
"Laphroaig 15":"Laphroaig",
"Laphroaig 18":"Laphroaig",
"Laphroaig 25 Cask Strength 2008":"Laphroaig",
"Laphroaig An Cuan Mor":"Laphroaig",
"Laphroaig Cairdeas 2012 Origin":"Laphroaig",
"Laphroaig Cairdeas 2013 Portwood":"Laphroaig",
"Laphroaig Cairdeas 2014 Amontillado":"Laphroaig",
"Laphroaig Cairdeas 2015":"Laphroaig",
"Laphroaig Cairdeas 2016 Madeira":"Laphroaig",
"Laphroaig Cairdeas 2017 Quarter Cask Cask Strength":"Laphroaig",
"Laphroaig Lore":"Laphroaig",
"Laphroaig PX Cask":"Laphroaig",
"Laphroaig Quarter Cask":"Laphroaig",
"Laphroaig Select":"Laphroaig",
"Laphroaig Triplewood":"Laphroaig",
"Larceny Small Batch Bourbon":"Larceny",
"Ledaig 10":"Ledaig",
"Ledaig 18":"Ledaig",
"Ledaig 7 /r/Scotch Community Cask":"Ledaig",
"Longrow 10":"Longrow",
"Longrow Peated":"Longrow",
"Longrow Red 11 Australian Shiraz":"Longrow",
"Longrow Red 11 Cabernet Sauvignon":"Longrow",
"Longrow Red 11 Fresh Port Cask":"Longrow",
"Longrow Red 12 Fresh Pinot Noir Cask":"Longrow",
"Longrow Red 13 Malbec":"Longrow",
"Lot No. 40":"Lot No. 40",
"Macallan 10 Fine Oak":"Macallan",
"Macallan 12":"Macallan",
"Macallan 12 Double Cask":"Macallan",
"Macallan 12 Sherry":"Macallan",
"Macallan 15 Fine Oak":"Macallan",
"Macallan 17 Fine Oak":"Macallan",
"Macallan 18":"Macallan",
"Macallan 18 Sherry":"Macallan",
"Macallan 25 Sherry":"Macallan",
"Macallan Classic Cut 2017":"Macallan",
"Macallan Edition No. 2":"Macallan",
"Macallan Gold":"Macallan",
"Macallan Rare Cask":"Macallan",
"Macallan Select Oak":"Macallan",
"Macallan Sherry Cask Strength":"Macallan",
"Mackinlay's Shackleton Rare Old Highland Malt Whisky":"Shackleton",
"Maker's Mark":"Maker's Mark",
"Maker's Mark 46":"Maker's Mark",
"Maker's Mark Cask Strength":"Maker's Mark",
"McClelland Islay":"McClelland's",
"Mellow Corn":"Mellow Corn",
"Michel Couvreur 12 Overaged Malt Whiskey":"Michel Couvreur",
"Michter's 10 Bourbon":"Michter's",
"Michter's 10 Rye":"Michter's",
"Michter's Barrel Strength Rye":"Michter's",
"Millstone 100 Rye":"Millstone",
"Monkey Shoulder":"Monkey Shoulder",
"Mortlach 15 Gordon & MacPhail":"Mortlach",
"Mortlach Rare Old":"Mortlach",
"Nikka Coffey Grain":"Nikka",
"Nikka Coffey Malt":"Nikka",
"Nikka Taketsuru 21":"Nikka",
"Nikka Whisky From The Barrel":"Nikka",
"Noah's Mill":"Noah's Mill",
"Oban 14":"Oban",
"Oban 18":"Oban",
"Oban Little Bay":"Oban",
"Old Ezra 101":"Old Ezra",
"Old Forester 1920":"Old Forester",
"Old Forester 86":"Old Forester",
"Old Forester Birthday Bourbon 2014":"Old Forester",
"Old Forester Signature":"Old Forester",
"Old Grand Dad 100 Bottled in Bond":"Old Grand Dad",
"Old Grand Dad 114":"Old Grand Dad",
"Old Pulteney 12":"Old Pulteney",
"Old Pulteney 17":"Old Pulteney",
"Old Pulteney 21":"Old Pulteney",
"Old Rip Van Winkle 10":"Van Winkle",
"Old Weller Antique 107":"W.L. Weller",
"Orphan Barrel Barterhouse 20":"Orphan Barrel",
"Pappy Van Winkle Family Reserve Bourbon 15":"Van Winkle",
"Pappy Van Winkle Family Reserve Bourbon 20":"Van Winkle",
"Pappy Van Winkle Family Reserve Bourbon 23":"Van Winkle",
"Parker's Heritage Collection 6th: Blend of Mashbills":"Parker's Heritage",
"Parker's Heritage Collection 7th: Promise of Hope":"Parker's Heritage",
"Parker's Heritage Collection 8th: Wheat Whiskey":"Parker's Heritage",
"Parker's Heritage Collection 9th: Malt Whiskey":"Parker's Heritage",
"Pig's Nose":"Pig's Nose",
"Pikesville Rye":"Pikesville",
"Port Ellen 32 12th Release":"Port Ellen",
"Rebel Yell 10 Single Barrel":"Rebel Yell",
"Redbreast 12":"Redbreast",
"Redbreast 12 Cask Strength":"Redbreast",
"Redbreast 15":"Redbreast",
"Redbreast 21":"Redbreast",
"Redbreast Lustau Edition":"Redbreast",
"Rittenhouse Rye 100":"Rittenhouse",
"Rock Hill Farms Single Barrel Bourbon":"Rock Hill",
"Rowan's Creek":"Rowan's Creek",
"Royal Lochnagar 12":"Royal Lochnagar",
"Russell's Reserve 10":"Russell's Reserve",
"Russell's Reserve Single Barrel Bourbon":"Russell's Reserve",
"Russell's Reserve Single Barrel Rye":"Russell's Reserve",
"Sazerac Rye":"Sazerac",
"Scapa 16":"Scapa",
"Sheep Dip":"Sheep Dip",
"Singleton of Glendullan 12":"The Singleton",
"Smokehead":"Smokehead",
"Smooth Ambler Old Scout Bourbon 10":"Smooth Ambler",
"Smooth Ambler Old Scout Bourbon 7":"Smooth Ambler",
"Smooth Ambler Old Scout Rye 7":"Smooth Ambler",
"Smooth Ambler Old Scout Rye 8":"Smooth Ambler",
"Speyburn 10":"Speyburn",
"Springbank 10":"Springbank",
"Springbank 10 100 Proof":"Springbank",
"Springbank 12 Burgundy":"Springbank",
"Springbank 12 Cask Strength":"Springbank",
"Springbank 12 Cask Strength Batch 7":"Springbank",
"Springbank 15":"Springbank",
"Springbank 16 Local Barley":"Springbank",
"Springbank 17 Sherry Wood":"Springbank",
"Springbank 18":"Springbank",
"Springbank 21":"Springbank",
"Stagg Jr.":"Stagg Jr.",
"Stagg Jr. Batch #9":"Stagg Jr.",
"Stranahan's Colorado Whiskey":"Stranahan's",
"Talisker 10":"Talisker",
"Talisker 175th Anniversary":"Talisker",
"Talisker 18":"Talisker",
"Talisker 25":"Talisker",
"Talisker 57° North":"Talisker",
"Talisker Distiller's Edition 2012":"Talisker",
"Talisker Port Ruighe":"Talisker",
"Talisker Storm":"Talisker",
"Tamdhu 10":"Tamdhu",
"Tamdhu 8 Signatory Cask Strength":"Tamdhu",
"Teeling Small Batch":"Teeling",
"Thomas H. Handy 2013":"Thomas H. Handy",
"Thomas H. Handy 2014":"Thomas H. Handy",
"Thomas H. Handy 2016":"Thomas H. Handy",
"Tobermory 10":"Tobermory",
"Tobermory 15":"Tobermory",
"Tomatin 12":"Tomatin",
"Tomatin 14 Portwood":"Tomatin",
"Tomatin 18":"Tomatin",
"Tomintoul 16":"Tomintoul",
"Té Bheag":"Té Bheag",
"Van Winkle Family Reserve Rye 13":"Van Winkle",
"Van Winkle Special Reserve 12 Lot B":"Van Winkle",
"Very Old Barton Bottled In Bond":"Very Old Barton",
"W.L. Weller 12":"W.L. Weller",
"W.L. Weller Special Reserve":"W.L. Weller",
"Westland Sherry Wood":"Westland",
"WhistlePig 10 Straight Rye":"WhistlePig",
"Wild Turkey 101":"Wild Turkey",
"Wild Turkey 101 Rye":"Wild Turkey",
"Wild Turkey 81":"Wild Turkey",
"Wild Turkey Decades":"Wild Turkey",
"Wild Turkey Forgiven":"Wild Turkey",
"Wild Turkey Kentucky Spirit":"Wild Turkey",
"Wild Turkey Rare Breed":"Wild Turkey",
"Willett Family Estate Rye 2y":"Willett",
"Willett Family Estate Rye 3y":"Willett",
"Willett Family Estate Rye 4y":"Willett",
"William Larue Weller 2013":"William Larue Weller",
"William Larue Weller 2016":"William Larue Weller",
"Woodford Reserve Distiller's Select":"Woodford Reserve",
"Woodford Reserve Double Oaked":"Woodford Reserve",
"Yamazaki 12":"Yamazaki",
"Yamazaki 18":"Yamazaki",
"Yellow Spot":"Yellow Spot"}