dist_dict = {"1792":"Barton 1792",
"Aberfeldy":"Aberfeldy",
"Aberlour":"Aberlour",
"Alberta Premium":"Alberta Premium",
"Amrut":"Amrut",
"AnCnoc":"Knockdhu",
"Angel's Envy":"Angel's Envy",
"Ardbeg":"Ardbeg",
"Ardmore":"Ardmore",
"Arran":"Arran",
"Auchentoshan":"Auchentoshan",
"Aultmore":"Aultmore",
"Baker's":"Jim Beam",
"Balblair":"Balblair",
"Balcones":"Balcones",
"Balvenie":"Balvenie",
"Basil Hayden's":"Jim Beam",
"BenRiach":"BenRiach",
"Benrinnes":"Benrinnes",
"Benromach":"Benromach",
"Bernheim":"Heaven Hill",
"Black Bottle":"Blended (Scotch)",
"Black Maple Hill":"Sourced (Bourbon)",
"Blanton's":"Buffalo Trace",
"Booker's":"Jim Beam",
"Bowmore":"Bowmore",
"Breckenridge":"Breckenridge",
"Bruichladdich":"Bruichladdich",
"Buchanan's":"Blended (Scotch)",
"Buffalo Trace":"Buffalo Trace",
"Bulleit":"Four Roses",
"Bunnahabhain":"Bunnahabhain",
"Bushmills":"Old Bushmills",
"Caol Ila":"Caol Ila",
"Cardhu":"Cardhu",
"Chivas":"Blended (Scotch)",
"Clynelish":"Clynelish",
"Collingwood":"Blended (Canadian)",
"Colonel E.H. Taylor":"Buffalo Trace",
"Compass Box":"Blended (Scotch)",
"Connemara":"Kilbeggan",
"Cragganmore":"Cragganmore",
"Craigellachie":"Craigellachie",
"Crown Royal":"Blended (Canadian)",
"Cutty Sark":"Blended (Scotch)",
"Dalmore":"Dalmore",
"Dalwhinnie":"Dalwhinnie",
"Deanston":"Deanston",
"Dewar's":"Blended (Scotch)",
"Dimple Pinch":"Blended (Scotch)",
"Eagle Rare":"Buffalo Trace",
"Edradour":"Edradour",
"Elijah Craig":"Heaven Hill",
"Elmer T. Lee":"Buffalo Trace",
"Evan Williams":"Heaven Hill",
"Famous Grouse":"Blended (Scotch)",
"Finlaggan":"Blended (Scotch)",
"Forty Creek":"Blended (Canadian)",
"Four Roses":"Four Roses",
"George Dickel":"Cascade Hollow",
"George T. Stagg":"Buffalo Trace",
"Glen Garioch":"Glen Garioch",
"Glen Grant":"Glen Grant",
"Glen Moray":"Glen Moray",
"GlenDronach":"GlenDronach",
"Glenfarclas":"Glenfarclas",
"Glenfiddich":"Glenfiddich",
"Glengoyne":"Glengoyne",
"Glenkinchie":"Glenkinchie",
"Glenlivet":"Glenlivet",
"Glenmorangie":"Glenmorangie",
"Glenrothes":"Glenrothes",
"Green Spot":"Midleton",
"Hakushu":"Hakushu",
"Hazelburn":"Springbank",
"Heaven Hill":"Heaven Hill",
"Henry McKenna":"Heaven Hill",
"Hibiki":"Blended (Japanese)",
"High West":"High West",
"Highland Park":"Highland Park",
"J.P. Wiser's":"Hiram Walker & Sons",
"J&B Rare":"Blended (Scotch)",
"Jack Daniels":"Jack Daniels",
"Jameson":"Midleton",
"Jefferson's":"Jefferson's",
"Jim Beam":"Jim Beam",
"Johnnie Walker":"Blended (Scotch)",
"Johnny Drum":"Willett",
"Jura":"Jura",
"Kavalan":"Kavalan",
"Kilchoman":"Kilchoman",
"Kilkerran":"Glengyle",
"Knob Creek":"Jim Beam",
"Lagavulin":"Lagavulin",
"Laphroaig":"Laphroaig",
"Larceny":"Heaven Hill",
"Ledaig":"Tobermory",
"Longrow":"Springbank",
"Lot No. 40":"Hiram Walker & Sons",
"Macallan":"Macallan",
"Maker's Mark":"Jim Beam",
"McClelland's":"Blended (Scotch)",
"Mellow Corn":"Heaven Hill",
"Michel Couvreur":"Blended (Scotch)",
"Michter's":"Michter's",
"Millstone":"Zuidam",
"Monkey Shoulder":"Blended (Scotch)",
"Mortlach":"Mortlach",
"Nikka":"Yoichi",
"Noah's Mill":"Willett",
"Oban":"Oban",
"Old Ezra":"Luxco",
"Old Forester":"Brown-Forman",
"Old Grand Dad":"Jim Beam",
"Old Pulteney":"Old Pulteney",
"Orphan Barrel":"Sourced (Bourbon)",
"Parker's Heritage":"Heaven Hill",
"Pig's Nose":"Blended (Scotch)",
"Pikesville":"Heaven Hill",
"Port Ellen":"Port Ellen",
"Rebel Yell":"Luxco",
"Redbreast":"Midleton",
"Rittenhouse":"Heaven Hill",
"Rock Hill":"Buffalo Trace",
"Rowan's Creek":"Willett",
"Royal Lochnagar":"Royal Lochnagar",
"Russell's Reserve":"Wild Turkey",
"Sazerac":"Buffalo Trace",
"Scapa":"Scapa",
"Shackleton":"Blended (Scotch)",
"Sheep Dip":"Blended (Scotch)",
"Smokehead":"Blended (Scotch)",
"Smooth Ambler":"Sourced (Bourbon)",
"Speyburn":"Speyburn",
"Springbank":"Springbank",
"Stagg Jr.":"Buffalo Trace",
"Stranahan's":"Stranahan's",
"Talisker":"Talisker",
"Tamdhu":"Tamdhu",
"Té Bheag":"Blended (Scotch)",
"Teeling":"Teeling",
"The Famous Grouse":"Blended (Scotch)",
"The Singleton":"Glendullan",
"Thomas H. Handy":"Buffalo Trace",
"Tobermory":"Tobermory",
"Tomatin":"Tomatin",
"Tomintoul":"Tomintoul",
"Van Winkle":"Buffalo Trace",
"Very Old Barton":"Barton 1792",
"W.L. Weller":"Buffalo Trace",
"Westland":"Westland",
"WhistlePig":"Sourced (Rye)",
"Wild Turkey":"Wild Turkey",
"Willett":"Willett",
"William Larue Weller":"Buffalo Trace",
"Woodford Reserve":"Woodford Reserve",
"Yamazaki":"Yamazaki",
"Yellow Spot":"Midleton"}