owner_dict = {"Aberfeldy":"Bacardi",
"Aberlour":"Pernod Ricard",
"Alberta Premium":"Beam Suntory",
"Amrut":"Amrut",
"Angel's Envy":"Bacardi",
"Ardbeg":"LVMH",
"Ardmore":"Beam Suntory",
"Arran":"Arran",
"Auchentoshan":"Beam Suntory",
"Aultmore":"Bacardi",
"Balblair":"Inver House",
"Balcones":"Balcones",
"Balvenie":"William Grant & Sons",
"1792":"Sazerac",
"Very Old Barton":"Sazerac",
"BenRiach":"Brown-Forman",
"Benrinnes":"Diageo",
"Benromach":"Gordon & MacPhail",
"Black Bottle":"Distell Group",
"The Famous Grouse":"Edrington",
"Chivas":"Pernod Ricard",
"Collingwood":"Brown-Forman",
"Compass Box":"Compass Box",
"Crown Royal":"Diageo",
"Cutty Sark":"Edrington",
"Dewar's":"Bacardi",
"Dimple Pinch":"Diageo",
"Famous Grouse":"Edrington",
"Forty Creek":"Campari",
"Hibiki":"Beam Suntory",
"J&B Rare":"Diageo",
"Johnnie Walker":"Diageo",
"Shackleton":"Whyte & Mackay",
"McClelland's":"Beam Suntory",
"Monkey Shoulder":"William Grant & Sons",
"Pig's Nose":"Ian Macleod",
"Sheep Dip":"Ian Macleod",
"Té Bheag":"Praban na Linne",
"Bowmore":"Beam Suntory",
"Breckenridge":"Breckenridge",
"Old Forester":"Brown-Forman",
"Woodford Reserve":"Brown-Forman",
"Bruichladdich":"Remy Cointreau",
"Buchanan's":"Diageo",
"Blanton's":"Sazerac Company",
"Buffalo Trace":"Sazerac Company",
"Colonel E.H. Taylor":"Sazerac Company",
"Eagle Rare":"Sazerac Company",
"Elmer T. Lee":"Sazerac Company",
"George T. Stagg":"Sazerac Company",
"Van Winkle":"Sazerac Company",
"W.L. Weller":"Sazerac Company",
"Rock Hill":"Sazerac",
"Sazerac":"Sazerac Company",
"Stagg Jr.":"Sazerac Company",
"Thomas H. Handy":"Sazerac",
"William Larue Weller":"Sazerac Company",
"Bunnahabhain":"Distell Group",
"Caol Ila":"Diageo",
"Cardhu":"Diageo",
"George Dickel":"Diageo",
"Clynelish":"Diageo",
"Cragganmore":"Diageo",
"Craigellachie":"Bacardi",
"Dalmore":"Whyte & Mackay",
"Dalwhinnie":"Diageo",
"Deanston":"Distell Group",
"Edradour":"Signatory Vintage",
"Bulleit":"Diageo",
"Four Roses":"Kirin Company",
"Glen Garioch":"Beam Suntory",
"Glen Grant":"Compari",
"Glen Moray":"La Martiniquaise",
"GlenDronach":"Brown-Forman",
"The Singleton":"Diageo",
"Glenfarclas":"Sazerac Company",
"Glenfiddich":"William Grant & Sons",
"Glengoyne":"Ian Macleod",
"Kilkerran":"J & A Mitchell & Company",
"Glenkinchie":"Diageo",
"Glenlivet":"Pernod Ricard",
"Glenmorangie":"LVMH",
"Glenrothes":"Edrington",
"Hakushu":"Beam Suntory",
"Bernheim":"Heaven Hill",
"Elijah Craig":"Heaven Hill",
"Evan Williams":"Heaven Hill",
"Heaven Hill":"Heaven Hill",
"Henry McKenna":"Heaven Hill",
"Larceny":"Heaven Hill",
"Mellow Corn":"Heaven Hill",
"Parker's Heritage":"Heaven Hill",
"Pikesville":"Heaven Hill",
"Rittenhouse":"Heaven Hill",
"High West":"Constellation Brands",
"Highland Park":"Edrington",
"J.P. Wiser's":"Pernod Ricard",
"Jack Daniels":"Brown-Forman",
"Jefferson's":"Castle Brands",
"Baker's":"Beam Suntory",
"Basil Hayden's":"Beam Suntory",
"Booker's":"Beam Suntory",
"Jim Beam":"Beam Suntory",
"Knob Creek":"Beam Suntory",
"Maker's Mark":"Beam Suntory",
"Old Grand Dad":"Beam Suntory",
"Jura":"Whyte & Mackay",
"Kavalan":"King Car Group",
"Connemara":"Beam Suntory",
"Kilchoman":"Kilchoman",
"AnCnoc":"Inver House",
"Lagavulin":"Diageo",
"Laphroaig":"Beam Suntory",
"Ledaig":"Distell Group",
"Lot No. 40":"Pernod Ricard",
"Old Ezra":"Luxco",
"Rebel Yell":"Luxco",
"Macallan":"Edrington",
"Michter's":"Michter's",
"Green Spot":"Pernod Ricard",
"Jameson":"Pernod Ricard",
"Redbreast":"Pernod Ricard",
"Yellow Spot":"Pernod Ricard",
"Mortlach":"Diageo",
"Oban":"Diageo",
"Bushmills":"Proximo",
"Old Pulteney":"Inver House",
"Port Ellen":"Diageo",
"Royal Lochnagar":"Diageo",
"Scapa":"Pernod Ricard",
"Black Maple Hill":"CVI Brands",
"Finlaggan":"Vintage Malt Whisky Company",
"Michel Couvreur":"Michel Couvreur",
"Orphan Barrel":"Orphan Barrel",
"Smokehead":"Ian Macleod",
"Smooth Ambler":"Pernod Ricard",
"WhistlePig":"WhistlePig",
"Speyburn":"Inver House",
"Hazelburn":"J & A Mitchell & Company",
"Longrow":"J & A Mitchell & Company",
"Springbank":"J & A Mitchell & Company",
"Stranahan's":"Proximo",
"Talisker":"Diageo",
"Tamdhu":"Ian Macleod",
"Teeling":"Teeling",
"Tobermory":"Distell Group",
"Tomatin":"Takara Shuzo",
"Tomintoul":"Angus Dundee",
"Westland":"Westland",
"Russell's Reserve":"Campari",
"Wild Turkey":"Campari",
"Johnny Drum":"Willett",
"Noah's Mill":"Willett",
"Rowan's Creek":"Willett",
"Willett":"Willett",
"Yamazaki":"Beam Suntory",
"Nikka":"Nikka",
"Millstone":"Zuidam"}