type_dict = {   "84":	                    "Other",
                "94":	                    "Other",
                " Highlands":	            "Scotch (Highlands)",
                "America":	                "American Whiskey",
                "American":	                "American Whiskey",
                "American craft Whiskey":	"American Whiskey",
                "American Single Malt":	    "American Whiskey",
                "American Whiskey":	        "American Whiskey",
                "Argentina":	            "World",
                "Argentina ": 	            "World",
                "Armagnac":	                "World",
                "Australia":	            "World",
                "Belgium":	                "World",
                "Blend":	                "Scotch (Blend)",
                "blend":	                "Scotch (Blend)",
                "Blend ": 	                "Scotch (Blend)",
                "blend (Islay)":	        "Scotch (Blend)",
                "blended malt":	            "Scotch (Blend)",
                "Blended malt":	            "Scotch (Blend)",
                "Blended Malt":	            "Scotch (Blend)",
                "Blended Speyside Scotch":	"Scotch (Blend)",
                "Borubon":	                "Bourbon",
                "Boubon":	                "Bourbon",
                "Bourbon":	                "Bourbon",
                "bourbon":	                "Bourbon",
                "Bourbon ": 	            "Bourbon",
                "Bourbon/America":	        "Bourbon",
                "bouron":	                "Bourbon",
                "Burma":	                "World",
                "Cambeltown":	            "Scotch (Campbeltown)",
                "Cambletown":	            "Scotch (Campbeltown)",
                "Campbeltown":	            "Scotch (Campbeltown)",
                "campbeltown":	            "Scotch (Campbeltown)",
                "Campbeltown ": 	        "Scotch (Campbeltown)",
                "Campbeltown Scotch":	    "Scotch (Campbeltown)",
                "Campeltown":	            "Scotch (Campbeltown)",
                "Campletown":	            "Scotch (Campbeltown)",
                "Canada":	                "Canadian Whisky",
                "canada":	                "Canadian Whisky",
                "Canada ": 	                "Canadian Whisky",
                "Canada Rye":	            "Canadian Whisky",
                "China":	                "World",
                "Corn":	                    "Other",
                "Corn Whiskey":	            "Other",
                "Czech":	                "World",
                "Czech Republic":	        "World",
                "Dominican Republic":	    "World",
                "Egypt":	                "World",
                "England":	                "World",
                "Finland":	                "World",
                "France":	                "World",
                "Germany":	                "World",
                "Grain":	                "Other",
                "Grain / Lowland":	        "Other",
                "Highland":	                "Scotch (Highlands)",
                "highland":	                "Scotch (Highlands)",
                "Highland ": 	            "Scotch (Highlands)",
                "Highland Scotch":	        "Scotch (Highlands)",
                "Highland Scotch ":	        "Scotch (Highlands)",
                "Highland Single Malt":	    "Scotch (Highlands)",
                "Highlands":	            "Scotch (Highlands)",
                "Highlands ":	            "Scotch (Highlands)",
                "Highlands?":	            "Scotch (Highlands)",
                "Home":	                    "Other",
                "https://www.reddit.com/r/bourbon/comments/d0n9yj/review_244_old_forester_rye/?st=k08nucm9&sh=f362a126":	"Other",
                "https://www.reddit.com/r/bourbon/comments/dcb2ub/review_144146_mystery_sample_series_sample_46/":	        "Other",
                "Iceland":	                "World",
                "India":	                "World",
                "Indian Single Malt":	    "World",
                "Ireland":	                "Irish Whiskey",
                "Irish":	                "Irish Whiskey",
                "Irish Blend":	            "Irish Whiskey",
                "Island":	                "Scotch (Islands)",
                "Island ":	                "Scotch (Islands)",
                "Island (Mull)":	        "Scotch (Islands)",
                "Island (Orkney)":	        "Scotch (Islands)",
                "Island (Skye)":	        "Scotch (Islands)",
                "Island Scotch":	        "Scotch (Islands)",
                "Islands":	                "Scotch (Islands)",
                "Islay":	                "Scotch (Islay)",
                "Islay ":	                "Scotch (Islay)",
                "islay":	                "Scotch (Islay)",
                "Islay Scotch":	            "Scotch (Islay)",
                "Isle of Arran":	        "Scotch (Islands)",
                "Isle of Jura":	            "Scotch (Islands)",
                "Isle of Mull":	            "Scotch (Islands)",
                "Isle of Skye":	            "Scotch (Islands)",
                "Israel":	                "World",
                "Italy":	                "World",
                "Jamaica":	                "World",
                "Japan":	                "Japan",
                "Kentucky":	                "Bourbon",
                "Light Whiskey":	        "Other",
                "Liqueur":	                "Other",
                "Lowland":	                "Scotch (Lowlands)",
                "Lowland / Grain":	        "Scotch (Lowlands)",
                "Lowland Grain":	        "Scotch (Lowlands)",
                "Lowlands":	                "Scotch (Lowlands)",
                "Netherlands":	            "World",
                "Netherlands ":	            "World",
                "New Zealand":	            "World",
                "Orkney":	                "Scotch (Islands)",
                "Orkney Islands":	        "Scotch (Islands)",
                "Other":                    "Other",
                "Poland":	                "World",
                "Russia":	                "World",
                "Rye":	                    "Rye",
                "rye":	                    "Rye",
                "Scotch":	                "Scotch (Blend)",
                "Scotland (blended malt)":	"Scotch (Blend)",
                "Single Grain Scotch":	    "Scotch (Blend)",
                "Single Grain Scotch Whisky":	"Scotch (Blend)",
                "Skye":	                    "Scotch (Islands)",
                "South Africa":	            "World",
                "Spain":	                "World",
                "Speyside":	                "Scotch (Speyside)",
                "speyside":	                "Scotch (Speyside)",
                "Speyside ": 	            "Scotch (Speyside)",
                "Speyside Scotch":	        "Scotch (Speyside)",
                "Sweden":	                "World",
                "Switzerland":	            "World",
                "Taiwan":	                "World",
                "Taiwan ": 	                "World",
                "Tasmania":	                "World",
                "Tennessee":	            "American Whiskey",
                "TOModera":	                "Other",
                "Utah Whiskey":	            "American Whiskey",
                "Wales":	                "Other",
                "West Highland Single Malt":	"Scotch (Highlands)",
                "Wheat":	                "Other",
                "White":	                "Other",
                "World":	                "World"}